train: ../VisDrone/val/images
val: ../VisDrone/val/images

nc: 10

# Classes
names:
  0: pedestrian
  1: people
  2: bicycle
  3: car
  4: van
  5: truck
  6: tricycle
  7: awning-tricycle
  8: bus
  9: motor